[package]
name = "program"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "3.0.0"
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"
thiserror = "2.0.15"
